# Copyright Siemens 2024
apiVersion: v2
name: opcenter-factory-config-helm
description: A Helm chart for Opcenter Execution Core Factory configuration (pre-deploy)
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.7.0

# Opcenter Core Version
appVersion: "2410"
