apiVersion: v1
kind: ConfigMap
metadata:
  name: opcenter-deploy-config
data:
  {{ if eq .Values.cloudProvider "Azure" }}
  OPCORE_METADATA_PATH: C:\opcenter-metadata\{{ .Values.config.metadataPath }}
  {{ end }}
  {{ if eq .Values.cloudProvider "AWS" }}
  OPCORE_METADATA_PATH: \\file-share-service.{{ .Values.config.sharedNamespace }}.svc.cluster.local\metadata\{{ .Values.config.metadataPath }}
  {{ end }}