# Copyright Siemens 2024
{{- if .Values.appServer.ipIngress.enabled -}}
{{- $svcPort := .Values.appServer.service.port -}}
{{- if and .Values.appServer.ipIngress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.appServer.ipIngress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.appServer.ipIngress.annotations "kubernetes.io/ingress.class" .Values.appServer.ipIngress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: app-server-ingress
  labels:
    {{- include "opcenter-core.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /CamstarAppServer/$2
    nginx.ingress.kubernetes.io/app-root: /CamstarAppServer
  {{- with .Values.appServer.ipIngress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.appServer.ipIngress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.appServer.ipIngress.className }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: /CamstarAppServer(/|$)(.*)
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: app-server
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: app-server
              servicePort: {{ $svcPort }}
              {{- end }}
{{- end }}