# Copyright Siemens 2024
apiVersion: v1
kind: Secret
metadata:
  name: opcenter-appserver-secrets
type: Opaque
data:
  {{- if .Values.appServer.connectServiceAccount.enabled}}
  OPCORE_SERVICE_ACCOUNT_USERNAME: {{ .Values.appServer.connectServiceAccount.username | b64enc }}
  OPCORE_SERVICE_ACCOUNT_PASSWORD: {{ .Values.appServer.connectServiceAccount.password | b64enc }}
{{- end }}
{{- if .Values.appServer.connectRestApi.username}}
  OPCORE_RESTAPI_USERNAME: {{ .Values.appServer.connectRestApi.username | b64enc }}
  OPCORE_RESTAPI_PASSWORD: {{ .Values.appServer.connectRestApi.password | b64enc }}
{{- end}}