# Copyright Siemens 2024
apiVersion: v1
kind: Service
metadata:
  name: app-server
  labels:
    {{- include "opcenter-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.appServer.service.type }}
  ports:
    - port: {{ .Values.appServer.service.port }}
  selector:
    {{- include "opcenter-core.appServer.selectorLabels" . | nindent 4 }}