# Copyright Siemens 2024
apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    {{- include "opcenter-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.portal.service.type }}
  ports:
    - port: {{ .Values.portal.service.port }}
  selector:
    {{- include "opcenter-core.portal.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP