{{- if .Values.notificationService.serviceAccount.create -}}
# Copyright Siemens 2024
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  labels:
    {{- include "opcenter-core.labels" . | nindent 4 }}
  {{- with .Values.notificationService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
