# Copyright Siemens 2024
{{- if or .Values.database.createSecret .Values.connectMOM.createSecret}}
apiVersion: v1
kind: Secret
metadata:
  name: opcenter-db-secrets
type: Opaque
data:
  {{- if .Values.database.createSecret}}
  OPCORE_DB_PASSWORD: {{ .Values.database.password | b64enc }}
  OPCORE_DB_SCHEMA: {{ .Values.database.schema | b64enc }}
  OPCORE_DB_USERNAME: {{ .Values.database.username | b64enc }}
  {{- end }}
  {{- if .Values.connectMOM.createSecret}}
  {{- if .Values.connectMOM.passphrase}}
  OPCORE_MIO_PASSPHRASE: {{ .Values.connectMOM.passphrase | b64enc }}
  {{- end }}
  {{- if .Values.connectMOM.password}}
  OPCORE_MIO_PASSWORD: {{ .Values.connectMOM.password | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}