# AWS: PV and PVC at the Shared level
# Azure: PV and PVC at the Factory level
# Copyright Siemens 2024
{{ if eq .Values.cloudProvider "Azure" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opcenter-metadata-pvc-{{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
{{ end }}