{{- if and .Values.odsDatabase.enabled .Values.odsDatabase.createSecret }}
# Copyright Siemens 2024
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opcenter-core-dbupdate.SecretName" . }}
type: Opaque
data:
  OPCORE_ODSDB_PASSWORD: {{ .Values.odsDatabase.password | b64enc }}
  OPCORE_ODSDB_SCHEMA: {{ .Values.odsDatabase.schema | b64enc }}
  OPCORE_ODSDB_USERNAME: {{ .Values.odsDatabase.username | b64enc }}
{{- end }}