# Copyright Siemens 2024
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-services
  labels:
    {{- include "opcenter-core.labels" . | nindent 4 }}
spec:
  {{- if not .Values.securityServices.autoscaling.enabled }}
  replicas: {{ .Values.securityServices.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  selector:
    matchLabels:
      {{- include "opcenter-core.securityServices.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.securityServices.podAnnotations | nindent 8 }}
      labels:
        {{- include "opcenter-core.securityServices.selectorLabels" . | nindent 8 }}
        {{- with .Values.securityServices.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.securityServices.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: security-services
      securityContext:
        {{- toYaml .Values.securityServices.podSecurityContext | nindent 8 }}
      containers:
        - name: security-services
          securityContext:
            {{- toYaml .Values.securityServices.securityContext | nindent 12 }}
          image: "{{ .Values.securityServices.image.repository }}:{{ .Values.securityServices.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.securityServices.image.pullPolicy }}
          startupProbe:
            httpGet:
              path: "/CamstarSecurityServices/AuthenticationService.svc"
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: "/CamstarSecurityServices/AuthenticationService.svc"
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: OPCORE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opcenter-db-secrets
                  key: OPCORE_DB_PASSWORD
            - name: OPCORE_DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: opcenter-db-secrets
                  key: OPCORE_DB_SCHEMA
            - name: OPCORE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: opcenter-db-secrets
                  key: OPCORE_DB_USERNAME
            {{- if .Values.securityServices.extraEnv -}}
              {{ toYaml .Values.securityServices.extraEnv | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: opcenter-config
            - configMapRef:
                name: opcenter-deploy-config
            {{- if .Values.securityServices.extraEnvFrom -}}
              {{ toYaml .Values.securityServices.extraEnvFrom | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.securityServices.resources | nindent 12 }}
          volumeMounts:
		      {{- if eq .Values.cloudProvider "Azure" }}
            - name: opcenter-metadata
              mountPath: \opcenter-metadata
          {{- end }}
          {{- if .Values.securityServices.extraVolumeMounts -}}
            {{ toYaml .Values.securityServices.extraVolumeMounts | nindent 12 }}
          {{- end }}
      volumes:
      {{- if eq .Values.cloudProvider "Azure" }}
        - name: opcenter-metadata
          persistentVolumeClaim:
            claimName: opcenter-metadata-pvc-{{ .Release.Namespace }}
      {{ end }}
      {{- if .Values.securityServices.extraVolumes -}}
        {{ toYaml .Values.securityServices.extraVolumes | nindent 8 }}
      {{- end }}
      nodeSelector:
        "kubernetes.io/os": windows
        "kubernetes.azure.com/os-sku": Windows2022
        {{- with .Values.securityServices.nodeSelectors }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.securityServices.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityServices.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
