# Copyright Siemens 2024
apiVersion: v1
kind: Service
metadata:
  name: security-services
  labels:
    {{- include "opcenter-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.securityServices.service.type }}
  ports:
    - port: {{ .Values.securityServices.service.port }}
  selector:
    {{- include "opcenter-core.securityServices.selectorLabels" . | nindent 4 }}