# Copyright Siemens 2024
{{ if eq .Values.cloudProvider "Azure" }}
{{- if .Values.storage.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: opcenter-storage-secret
type: Opaque
data:
  azurestorageaccountname: {{ .Values.storage.secret.accountname | b64enc }}
  azurestorageaccountkey: {{ .Values.storage.secret.accountkey | b64enc }}
{{- end }}
{{ end }}