{{- if .Values.appServerSf.enabled -}}
{{- if .Values.appServerSf.ipIngress.enabled -}}
# Copyright Siemens 2024
{{- $svcPort := .Values.appServerSf.service.port -}}
{{- if and .Values.appServerSf.ipIngress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.appServerSf.ipIngress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.appServerSf.ipIngress.annotations "kubernetes.io/ingress.class" .Values.appServerSf.ipIngress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: app-server-sf-ingress
  labels:
    {{- include "opcenter-core.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /CamstarAppServerSf/$2
    nginx.ingress.kubernetes.io/app-root: /CamstarAppServerSf
  {{- with .Values.appServerSf.ipIngress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.appServerSf.ipIngress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.appServerSf.ipIngress.className }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: /CamstarAppServerSf(/|$)(.*)
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: app-server-sf
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: app-server-sf
              servicePort: {{ $svcPort }}
              {{- end }}
{{- end }}
{{- end }}